version: "3.8"
services: 
  ether_analyser:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
    environment:
      WAIT_HOSTS: mysql:3306
  mysql_server:
    image: mysql:8.0
    hostname: mysql
    ports:
      - 3306
    environment: 
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD